version: "3"
services:
  kong-database:
    image: postgres:9.4
    expose:
        - 5432
    environment:
        - POSTGRES_USER=kong
        - POSTGRES_DB=kong
  kong:
    image: kong:latest
    links:
      - kong-database
    expose:
      - 8000
      - 8001
      - 8443
      - 8444
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    volumes:
      - /usr/local/kong
  kong-dashboard:
    image: pgbi/kong-dashboard:v2
    links:
      - kong
    ports:
      - "9999:9999"
    command: -p 9999
